### ISSUE TITLE
filter for a package name

### ISSUE THREAD

**Issue by steadfasterX** [mjiricka/archnews#2]
it would be amazing if archnews could be enhanced in a way where it parses the news feed for one or more given package(s) and showing only the related output for it. e.g.:

`archnews --package openvpn,foo,bar`

This way one could see only relevant output for interesting packages.

_Note:
I want to use this before upgrading actually. So I want to freshen the databases first and then for each package found I want to use archnews to show relevant information_

**Comment by mjiricka** [comment]
Can you please send me URL of the package news feed? I do not know about any. Only about discussion under packages in AUR (unfortunately it looks like they have no RSS) and this list 
https://www.archlinux.org/packages/
but there are no messages.

**Comment by steadfasterX** [comment]
No. I just want to let archnews do what it currently does but just filter the output based on my installed packages.

what i wanted to do:

```
for pkg in $(pacman -Suq --print-format="%n");do
    archnews --package $pkg
done
```

 result will be something like this:

> archnews --package dtksettings
> archnews --package deepin-menu
OUTPUT from Arch news feed relating to deepin-menu
> archnews --package linux-lts
> archnews --package linux-lts-headers
> archnews --package perl-extutils-pkgconfig
> archnews --package qemu
OUTPUT from Arch news feed relating to qemu
> archnews --package qtkeychain
> archnews --package ruby

The idea is to fetch all news from the official arch news feed (as u currently do) but then filter it by the given package name and combined with the other issue I opened it (issue #1 ) archnews would show absolutely relevant information only

hope it is more clear now.. :)

**Comment by mjiricka** [comment]
I implemented `--grep` option. There is no information about which packages are affected (sometimes many like the news about dropping support for i686) in the feed. But it does not support colon for many options now… Maybe it would be possible to extend it to regex?

**Comment by steadfasterX** [comment]
**Great! MANY** thanks. Works like a charme (besides issue #3).

regex could be an option but when this becomes necessary I would open another issue ;)
so for me this can be closed now.

**Comment by steadfasterX** [comment]
I will add another issue if required but the following would be great:

when `--grep` find a news feed for a given string exit with returncode of **0** otherwise with **1**. This would make it possible to make an action depending on what the exitcode was..

**Comment by mjiricka** [comment]
Yes, in the latest version are following return codes: 0 = success & some entries were shown, 1 = no entries shown, 2 = error in arguments and 3 = some other error.

**Comment by mjiricka** [comment]
@steadfasterX I also wrote a man page! ;)) You can check it and give me a feedback.

    man -l archnews.1

**Comment by steadfasterX** [comment]
> Yes, in the latest version are following return codes: 0 = success & some entries were shown, 1 = no entries shown, 2 = error in arguments and 3 = some other error.

working perfectly thx!

> @steadfasterX I also wrote a man page! ;)) You can check it and give me a feedback.

very nice ;)

just some minor ones:
In FILES section you miss the ending encapsulating of

> then '~/.local/share/  is

Maybe you could enhance the description of `--since` so 1), 2) etc are each in a new line?

And you told me that the order of args is important? (https://github.com/mjiricka/archnews/issues/1#issuecomment-298187736) I would like to see that information in the manpage as well ;)

and I would suggest to also add the SEE ALSO section and pointing to this github repo :)
JM5C

Anyways this issue can be closed now :+1: :-)

**Comment by mjiricka** [comment]
> In FILES section you miss the ending encapsulating of

Oh yeah, thanks!

> Maybe you could enhance the description of --since so 1), 2) etc are each in a new line?

Yes, I wanted that too, but it clashed with my knowledge of TROFF ;)

> And you told me that the order of args is important? 

No, it is not. I was considering to make it important, but I found out it would be too difficult. Thats why I wrote into doc this:

    These  filters  can be combined (e.g. use --grep together with --num-entries), but --num-entries will be always applied as the last filter.

--since and --grep are orthogonal, so their order does not matter, but --num-entries will be always applied last no matter where it will be used on command line.
