### ISSUE TITLE
showing ALL news (-n 0 or -n 100000) shows last 10 entries only

### ISSUE THREAD

**Issue by steadfasterX** [mjiricka/archnews#3]
I tried to use -n and --num-entries but both showing the last 10 entries only
The reason for this is that the **RSS** feed shows only 10 entries and https://www.archlinux.org/feeds/ shows no other available option for this.

In opposite the human readable Arch news page https://www.archlinux.org/news/ shows really ALL content but it seems there is no feed available for it... and i found no way to display all news on 1 single page which would require to parse all page-X links as well..

It would be great to have this in archnews nevertheless but that requires a big change in parsing the data.. if you do not want to do this I would suggest to change the -n help message at least so it makes clear it will show only the latest X entries available in the **RSS** news feed and not necessarily really all available news.

**Comment by mjiricka** [comment]
Yes, of course the number is limited by number of entries in RSS. I added a note about it into help section and maybe I will document it also somewhere else. The real purpose of this script is really just checking news before upgrading system, not creating Arch news scrapping app :-)
