### ISSUE TITLE
How should --stdin work?

### ISSUE THREAD

**Issue by Jacobtey** [mjiricka/archnews#6]
Hi! 
archnews -i
How should it work?

**Comment by mjiricka** [comment]
I needed this option in `archnews_wrap` (see the code, there is an extensive comment why). If you already have the RSS, you can pipe it into archnews. E.g.:

    curl https://www.archlinux.org/feeds/news/ | archnews -i

**Comment by Jacobtey** [comment]
Oh! Thanx. It's really great

**Comment by mjiricka** [comment]
You're welcome :)
